#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string
FILE=/etc/nginx/sites-available/default
REDIRECT="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
F0F="error_page 404 /404.html;\n location = /404.html {\n root /usr/share/nginx/html;\n internal;\n}\n"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
service nginx start
sudo sed -i "37i $REDIRECT" $FILE
sudo sed -i "41i $F0F" $FILE
sudo service nginx restart
