#!/usr/bin/env bash
# Replace all occurrences of "8080" with "80" in  conf file. -i(in-place) -g(global=>replace all occurrences on each line). 
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart 
pkill -o nginx
