#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.

# Backup configuration files
sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
sudo cp /sudo etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Update Nginx configuration
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf

# Restart Nginx
sudo -u nginx service nginx restart

